### ISSUE TITLE
Can Bypass?

### ISSUE THREAD

**Issue by wulandrima1** [karankankaria/GDrive-X#3]
Error, Not Work..

https://gdrivex.herokuapp.com/embed.php?url=cjBjUlVEbUFWMkE4UWFYbmRIZEJDYWdNcFJ3dXNwc1liemkydGlCMW5ZTmx4T2VJZ2ZrQlFQek5GTi9OUExEKzBjQTZySmJTeDdpTnJsTnVUUjFidHVmSFo5M3NwTjNpVFF2NUcvRG01ZGM9&sub=&poster=

Sample Link Original. 
https://drive.google.com/file/d/1x8gjJD-d8ohM6N6BVl7cbfi26uJaFJEC/view

**Comment by karankankaria** [comment]
GDrive-X Tool is for playing video hosted on Google Photos and not for the video hosted o Google Drive. Please use Google Photos Video Link. It will work. Try this link: https://photos.google.com/share/AF1QipMTEPAiVF8t0YqLukflnOSQjwfd8ARIoT2h37AXvYO1uaWodbeiFoBUDuD_19tEbg/photo/AF1QipPA2Bq0JlAR9LoGD3mogsxSb9OZWEG4XqBDD4Rv?key=cjhUT0xrZjM5NGN2SVRLOVptZU5SMUlKV0lQYWpB

**Comment by wulandrima1** [comment]
oh.. sorry sir., im wrong..
i mind google drive..
